# Generated by Django 2.0.2 on 2018-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='measurement (optional)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='preparation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='preparation (optional)'),
        ),
    ]
