# Generated by Django 2.0.2 on 2018-03-01 08:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(help_text='enter time in minutes', verbose_name='cook time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='info',
            field=models.TextField(help_text='enter information about the recipe', verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='upload/recipe_photos', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='related',
            field=models.OneToOneField(blank=True, help_text='relate another recipe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeRelated', to='recipe.Recipe', verbose_name='related'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(help_text='enter total number of servings', verbose_name='servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shared',
            field=models.IntegerField(choices=[(0, 'Share'), (1, 'Private')], default=0, help_text='share the recipe with the community or mark it private', verbose_name='shared'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='separate with commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
