# Generated by Django 2.0.2 on 2018-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170212_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='about',
            field=models.TextField(blank=True, default='Tell everyone something about yourself', verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='None', help_text='What are ya?', max_length=5, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='location'),
        ),
    ]
